Repository istio/gogo-genproto, pull requests merged in 2019-10, with the labels that each got.

#24 Add gen-check target.
  Makefile
  Makefile.core.mk
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/license-lint.yml
  common/scripts/check_clean_repo.sh
Labels: cla: yes, size/M

#25 Fix the gen-check target.
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: cla: yes, size/XS

#26 Update common files.
  Makefile
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: cla: yes, size/M

#27 Add field_behavior to the generated protos
  Makefile.core.mk
  googleapis/google/api/field_behavior.pb.go
Labels: cla: yes, size/XS

#28 Update common files.
  Makefile
  Makefile.core.mk
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/.golangci.yml
  common/scripts/check_clean_repo.sh
  common/scripts/lint_go.sh
  common/scripts/report_build_info.sh
  licenses/cloud.google.com/go/LICENSE
  licenses/github.com/BurntSushi/toml/COPYING
  licenses/github.com/client9/misspell/LICENSE
  licenses/github.com/gogo/protobuf/LICENSE
  licenses/github.com/golang/glog/LICENSE
  licenses/github.com/golang/mock/LICENSE
  licenses/github.com/golang/protobuf/LICENSE
  licenses/github.com/google/go-cmp/LICENSE
  licenses/github.com/kisielk/errcheck/LICENSE
  licenses/github.com/kisielk/gotool/LICENSE
  licenses/golang.org/x/crypto/LICENSE
  licenses/golang.org/x/lint/LICENSE
  licenses/golang.org/x/net/LICENSE
  licenses/golang.org/x/oauth2/LICENSE
  licenses/golang.org/x/sync/LICENSE
  licenses/golang.org/x/sys/LICENSE
  licenses/golang.org/x/text/LICENSE
  licenses/golang.org/x/tools/LICENSE
  licenses/google.golang.org/appengine/LICENSE
  licenses/google.golang.org/genproto/LICENSE
  licenses/google.golang.org/grpc/LICENSE
  licenses/honnef.co/go/tools/LICENSE
Labels: cla: yes, size/XXL
