Repository istio/gogo-genproto, pull requests merged in 2019-08, with the labels that each got.

#16 Switch this repo to the build-tools container.
  .commonfiles.sha
  .golangci.yml
  BUGS-AND-FEATURE-REQUESTS.md
  CONTRIBUTING.md
  LICENSE
  Makefile
  Makefile.common.mk
  Makefile.core.mk
  Makefile.overrides.mk
  SUPPORT.md
  scripts/check_dockerfiles.sh
  scripts/check_license.sh
  scripts/run_gobindata.sh
  scripts/run_gofmt.sh
  scripts/run_golangci.sh
Labels: size/XL

#18 add google.api.expr
  Makefile.core.mk
  go.mod
  go.sum
  googleapis/google/api/expr/v1alpha1/cel_service.pb.go
  googleapis/google/api/expr/v1alpha1/checked.pb.go
  googleapis/google/api/expr/v1alpha1/conformance_service.pb.go
  googleapis/google/api/expr/v1alpha1/eval.pb.go
  googleapis/google/api/expr/v1alpha1/explain.pb.go
  googleapis/google/api/expr/v1alpha1/syntax.pb.go
  googleapis/google/api/expr/v1alpha1/value.pb.go
Labels: size/XXL

#20 Update common files.
  .commonfiles.sha
  Makefile
  Makefile.common.mk
  Makefile.core.mk
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/.golangci.yml
  common/config/.hadolint.yml
  common/config/.yamllint.yml
  common/scripts/gobuild.sh
  common/scripts/lint_copyright_banner.sh
  common/scripts/report_build_info.sh
  scripts/check_dockerfiles.sh
  scripts/lint_copyright_banner.sh
  scripts/run_gobindata.sh
  scripts/run_gofmt.sh
Labels: size/L
