Repository istio/gogo-genproto, pull requests merged in 2020-04, with the labels that each got.

#55 Automator: update common-files@master in istio/gogo-genproto@master
  Makefile
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, size/XS

#56 Automator: update common-files@master in istio/gogo-genproto@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#57 Automator: update common-files@master in istio/gogo-genproto@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, size/S

#58 Automator: update common-files@master in istio/gogo-genproto@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#59 Automator: update common-files@master in istio/gogo-genproto@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#60 Automator: update common-files@master in istio/gogo-genproto@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/S

#61 Automator: update common-files@master in istio/gogo-genproto@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#62 Automator: update common-files@master in istio/gogo-genproto@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#63 Automator: update common-files@master in istio/gogo-genproto@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
  k8s.io/api/apps/v1/generated.pb.go
  k8s.io/api/core/v1/generated.pb.go
  k8s.io/api/rbac/v1/generated.pb.go
Labels: auto-merge, cla: yes, size/XS

#64 Automator: update common-files@master in istio/gogo-genproto@master
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/check_no_modify.sh
  common/scripts/nomodify.md5
Labels: auto-merge, cla: yes, size/S

#65 Automator: update common-files@master in istio/gogo-genproto@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, size/S

#66 Automator: update common-files@master in istio/gogo-genproto@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#67 Automator: update common-files@master in istio/gogo-genproto@master
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/check_no_modify.sh
  common/scripts/nomodify.md5
Labels: auto-merge, cla: yes, size/S

#68 Add release managers as CODEOWNERS for release 1.6
  CODEOWNERS
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: cla: yes, size/XS

#69 Automator: update common-files@master in istio/gogo-genproto@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/S

#70 Automator: update common-files@master in istio/gogo-genproto@master
  common/.commonfiles.sha
  common/config/license-lint.yml
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#71 Automator: update common-files@master in istio/gogo-genproto@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, size/XS
