Repository istio/gogo-genproto, pull requests merged in 2020-07, with the labels that each got.

#97 Automator: update common-files@master in istio/gogo-genproto@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#98 Automator: update common-files@master in istio/gogo-genproto@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#99 Automator: update common-files@master in istio/gogo-genproto@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#100 Automator: update common-files@master in istio/gogo-genproto@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: auto-merge, cla: yes, size/S

#101 Automator: update common-files@release-1.6 in istio/gogo-genproto@release-1.6
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: auto-merge, cla: yes, size/S

#102 Automator: update common-files@master in istio/gogo-genproto@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#103 Automator: update common-files@master in istio/gogo-genproto@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: auto-merge, cla: yes, size/XS

#104 Automator: update common-files@master in istio/gogo-genproto@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: auto-merge, cla: yes, size/XS

#105 Automator: update common-files@master in istio/gogo-genproto@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#106 Automator: update common-files@master in istio/gogo-genproto@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, size/XS

#107 Automator: update common-files@master in istio/gogo-genproto@master
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/run.sh
Labels: auto-merge, cla: yes, size/S

#108 Automator: update common-files@master in istio/gogo-genproto@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: auto-merge, cla: yes, size/XS

#109 Automator: update common-files@master in istio/gogo-genproto@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#110 Automator: update common-files@master in istio/gogo-genproto@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#111 Automator: update common-files@master in istio/gogo-genproto@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: auto-merge, cla: yes, size/XS

#112 Set release managers as CODEOWNERS for release-1.7
  CODEOWNERS
Labels: cla: yes, size/XS

#113 update common
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#114 Automator: update common-files@master in istio/gogo-genproto@master
  common/.commonfiles.sha
  common/scripts/run.sh
Labels: auto-merge, cla: yes, size/XS

#115 Automator: update common-files@release-1.7 in istio/gogo-genproto@release-1.7
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#116 Automator: update common-files@master in istio/gogo-genproto@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#117 Automator: update common-files@master in istio/gogo-genproto@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS
