Repository istio/gogo-genproto, pull requests merged in 2021-12, with the labels that each got.

#308 Automator: update common-files@master in istio/gogo-genproto@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#309 Automator: update common-files@master in istio/gogo-genproto@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#310 Automator: update common-files@release-1.12 in istio/gogo-genproto@release-1.12
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#312 Automator: update common-files@master in istio/gogo-genproto@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#311 Update go.mod to 1.17; use updated same grpc lib
  go.mod
  go.sum
  licenses/google.golang.org/protobuf/LICENSE
Labels: size/L

#313 Automator: update common-files@master in istio/gogo-genproto@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#314 Automator: update common-files@master in istio/gogo-genproto@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#315 Automator: update common-files@release-1.12 in istio/gogo-genproto@release-1.12
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#316 Automator: update common-files@master in istio/gogo-genproto@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#317 Automator: update common-files@master in istio/gogo-genproto@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
