Repository istio/gogo-genproto, pull requests merged in 2021-01, with the labels that each got.

#178 Automator: update common-files@master in istio/gogo-genproto@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#179 Automator: update common-files@master in istio/gogo-genproto@master
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#180 Automator: update common-files@master in istio/gogo-genproto@master
  common/.commonfiles.sha
  common/scripts/run.sh
Labels: auto-merge, cla: yes, release-notes-none, size/S

#181 Automator: update common-files@master in istio/gogo-genproto@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#182 Automator: update common-files@master in istio/gogo-genproto@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#183 Automator: update common-files@master in istio/gogo-genproto@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#184 Update gogo protobuf to v1.3.2
  go.mod
  go.sum
Labels: cla: yes, size/M

#185 Automator: update common-files@master in istio/gogo-genproto@master
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#186 Automator: update common-files@master in istio/gogo-genproto@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#189 Automator: update common-files@release-1.9 in istio/gogo-genproto@release-1.9
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#187 Set release managers as CODEOWNERS for release-1.9
  CODEOWNERS
Labels: cla: yes, size/XS

#190 Automator: update common-files@release-1.9 in istio/gogo-genproto@release-1.9
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#191 run UPDATE_BRANCH=release-1.9 make update-common
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#192 Automator: update common-files@release-1.9 in istio/gogo-genproto@release-1.9
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#193 update common file for 1.9
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#195 Automator: update common-files@master in istio/gogo-genproto@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
  common/scripts/metallb.yaml
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/L

#196 Automator: update common-files@master in istio/gogo-genproto@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/S

#197 Automator: update common-files@master in istio/gogo-genproto@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#198 Automator: update common-files@master in istio/gogo-genproto@master
  .gitattributes
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#199 Automator: update common-files@master in istio/gogo-genproto@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#200 Automator: update common-files@release-1.9 in istio/gogo-genproto@release-1.9
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
  common/scripts/metallb.yaml
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/L

#201 Automator: update common-files@release-1.8 in istio/gogo-genproto@release-1.8
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
  common/scripts/metallb.yaml
Labels: auto-merge, cla: yes, release-notes-none, size/L

#202 Automator: update common-files@master in istio/gogo-genproto@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#203 Automator: update common-files@release-1.7 in istio/gogo-genproto@release-1.7
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#204 Automator: update common-files@master in istio/gogo-genproto@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS
