Repository istio/gogo-genproto, pull requests merged in 2022-02, with the labels that each got.

#337 Automator: update common-files@master in istio/gogo-genproto@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#339 Automator: update common-files@release-1.12 in istio/gogo-genproto@release-1.12
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#340 Automator: update common-files@release-1.13 in istio/gogo-genproto@release-1.13
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/lint_go.sh
  common/scripts/setup_env.sh
Labels: size/S, auto-merge, release-notes-none

#341 Automator: update common-files@master in istio/gogo-genproto@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#342 [release-1.13] Fix common files
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/lint_go.sh
  common/scripts/setup_env.sh
Labels: size/S

#343 Automator: update common-files@release-1.12 in istio/gogo-genproto@release-1.12
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#345 Automator: update common-files@master in istio/gogo-genproto@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#346 Automator: update common-files@master in istio/gogo-genproto@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/M, auto-merge, release-notes-none

#347 Automator: update common-files@master in istio/gogo-genproto@master
  common/.commonfiles.sha
  common/config/.hadolint.yml
Labels: size/XS, auto-merge, release-notes-none

#348 Automator: update common-files@release-1.12 in istio/gogo-genproto@release-1.12
  common/.commonfiles.sha
  common/config/.hadolint.yml
Labels: size/XS, auto-merge, release-notes-none

#349 Automator: update common-files@master in istio/gogo-genproto@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
